### ISSUE TITLE
BuckleScript 5.2.0 ( Using OCaml:4.02.3+BS ) version problem

### ISSUE THREAD

**Issue by swuecho** [ELLIOTTCABLE/bs-deriving#3]
`bsc -version failed`, and I can't invoke the correct executable! Got:
BuckleScript 5.2.0 ( Using OCaml:4.02.3+BS )

ppx-deriving/identify.js:18
throw new Error("`bsc -version` parsing failed")

**Comment by Coobaha** [comment]
https://github.com/ELLIOTTCABLE/ppx-deriving/pull/2 @ELLIOTTCABLE

**Comment by ELLIOTTCABLE** [comment]
Fixed in ELLIOTTCABLE/ppx-deriving@cba64f4820f642ab4c5ee6dbd834fc1ea1fb2720 and d7ea08eb8fa2df4df510394a85ed08ebb24fb048 (thanks, @Coobaha); which is now live as v44.1.0:

https://github.com/ELLIOTTCABLE/bs-deriving/releases/tag/v44.1.0

**Comment by swuecho** [comment]
works great! thanks
